# Supabase config optimized for CI: disable nonessential services
project_id = "env(SUPABASE_PROJECT_ID)"

[api]
enabled = true
port = "env(LOCAL_SUPABASE_API_PORT)"
schemas = ["public"]
extra_search_path = ["public", "extensions"]

[api.tls]
enabled = false

[db]
port = "env(LOCAL_SUPABASE_DB_PORT)"
shadow_port = "env(LOCAL_SUPABASE_DB_SHADOW_PORT)"
major_version = 15

[db.pooler]
enabled = false

[db.seed]
enabled = false
sql_paths = []

[realtime]
enabled = false

[studio]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = false

[auth]
enabled = true
site_url = "http://localhost"
additional_redirect_urls = ["http://localhost"]
enable_signup = false
enable_anonymous_sign_ins = false

[edge_runtime]
enabled = false

[analytics]
enabled = false

[experimental]
orioledb_version = ""

