name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  e2e:
    runs-on: ${{ github.repository == 'antiwork/helper' && 'ubicloud-standard-2' || 'ubuntu-latest' }}
    timeout-minutes: 60
    name: E2E (${{ matrix.shard }}/${{ strategy.job-total }})
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]
    env:
      CI: true
      OPENAI_API_KEY: test-openai-api-key
      FIRECRAWL_API_KEY: test-firecrawl-api-key
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-v1
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Setup E2E test environment
        run: ./scripts/setup-e2e-tests.sh

      - name: Run fail-fast on changed Playwright tests
        if: github.event_name == 'pull_request'
        run: ./scripts/e2e.sh playwright test --only-changed=origin/${{ github.base_ref }} --shard=${{ matrix.shard }}/${{ strategy.job-total }}

      - name: Run full Playwright suite
        if: github.event_name == 'push'
        run: ./scripts/e2e.sh playwright test --shard=${{ matrix.shard }}/${{ strategy.job-total }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shard }}
          path: blob-report
          retention-days: 30
